services:
  # 1. The Database Container
  db:
    image: postgres:16-alpine
    container_name: qdc_postgres
    restart: always
    environment:
      POSTGRES_DB: qdc_lims_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data even if container stops

  # 2. The LIMS App Container
  app:
    build: .
    container_name: qdc_lims_app
    restart: always
    ports:
      - "8080:8080" # Map computer's Port 80 (Standard Web) to App's 8080
    environment:
      # OVERRIDE the settings in application.properties
      # Note: 'db' here refers to the service name above, not localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/qdc_lims_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db # Wait for DB to start before starting App

# Create a permanent storage volume for the database
volumes:
  db_data:
